Load AWS e2e creds from secret manager
wix-playground/media-actions pull request #5
Opened 2022-05-09 12:20 UTC by Elad-Laufer

2022-05-09 16:49 UTC, golanpa requested changes

2022-05-09 16:49 UTC, golanpa commented on build/action.yml
> +          GITHUB_ACTIONS_E2E_AWS_CRED:${{ inputs.gcp-project-id }}/${{ inputs.e2e-aws-cred }}
where GITHUB_ACTIONS_E2E_AWS_CRED is used?

2022-05-09 16:49 UTC, golanpa commented on build-and-push/action.yml
> +          GITHUB_ACTIONS_E2E_AWS_CRED:${{ inputs.gcp-project-id }}/${{ inputs.e2e-aws-cred }}
where GITHUB_ACTIONS_E2E_AWS_CRED is used? 
I also see that you are using:

- name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ steps.secrets.outputs.GITHUB_ACTIONS_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ steps.secrets.outputs.GITHUB_ACTIONS_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

but GITHUB_ACTIONS_AWS_ACCESS_KEY_ID and GITHUB_ACTIONS_AWS_SECRET_ACCESS_KEY are not declared in the secrets step

2022-05-10 07:07 UTC, Elad-Laufer commented on build/action.yml
> +          GITHUB_ACTIONS_E2E_AWS_CRED:${{ inputs.gcp-project-id }}/${{ inputs.e2e-aws-cred }}
In builds that have e2e tests such as:

https://github.com/wix-private/mcloud-go-framework
https://github.com/wix-private/media-platform-goppelganger
https://github.com/wix-private/media-platform-upload-server

2022-05-10 07:08 UTC, Elad-Laufer commented on build-and-push/action.yml
> +          GITHUB_ACTIONS_E2E_AWS_CRED:${{ inputs.gcp-project-id }}/${{ inputs.e2e-aws-cred }}
Because they are used to push the image to ECR and not to run tests.

2022-05-11 10:48 UTC, golanpa approved these changes

2022-05-17 07:54 UTC, merged